base_url: http://www.grokpodcast.com
podcast_file_storage: http://media.grokpodcast.com/
google_analytics_code: UA-18562844-1
permalink:  pretty
markdown:   kramdown
exclude: ['bin', 'Rakefile', 'README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', 'config.rb', 'vendor']
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed

featured:
  title: "Swift"
  image: /images/2015/03/header-aceleradoras.jpg

collections:
  series:
    output: true
    permalink: /series/:path/

deploy:
  github_pages:
    target_repository: 'grokpodcast/site'

itunes:
  url: 'http://itunes.apple.com/br/podcast/grok-podcast/id393122038'

gems:
  - jekyll-redirect-from
