source 'https://rubygems.org'

gem 'jekyll',     '~> 1.0'
gem 'rdiscount',  '~> 1.6'
gem 'compass',    '~> 0.12'
gem 'hpricot',    '~> 0.8'
gem 'nokogiri',   '~> 1.6'
gem 'rake',				'~> 10.0'
gem 'aws-sdk',		'~> 1.11'
gem 'rspec', 			'~> 2.13'
